# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b36856f6817e2897b711e80a7476f9392267d0e215852dc26ccf3cbf708e071b8cc291964d7a8418ce45aec395b8c8b294c76c31c94f3afc4058106f246d4fd

test:
  secret_key_base: ebf7264d6d50b38f321bd2ee29259fa0e94cd770b752bd9572b3524cf9e2bef1a33e1233bfb7e517bed81d6029d15c6c45f84d92b6f49fe250e7fc6ce0cb02e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
